GC_SCENARIO=PROMOTION_PRESSURE
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.http-server.request-histogram=true
quarkus.micrometer.binder.http-server.histogram=true
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.system=true
