apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-cache-load
  labels:
    app: auth-cache-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-cache-load
  template:
    metadata:
      labels:
        app: auth-cache-load
    spec:
      containers:
        - name: wrk
          image: docker.io/williamyeh/wrk:latest
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "Starting wrk load...";
              sleep 10;
              while true; do
                wrk -t4 -c128 -d60s http://auth-cache-service:8080/work;
              done
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "2"
              memory: "256Mi"
