apiVersion: v1
kind: Namespace
metadata:
  name: chaos-test
---
apiVersion: batch/v1
kind: Job
metadata:
  name: heap-oom-prom-job
  namespace: chaos-test
  labels:
    app: heap-oom-prom-job
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: heap-oom-prom-job
    spec:
      restartPolicy: Never
      containers:
        - name: heap-oom-prom
          image: quay.io/causa-ai-hub/quarkus-heap-oom:heap-oom-prom
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=80 -XX:+CrashOnOutOfMemoryError"
